apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
      - name: reddit-app
        image: gcr.io/mlops-458623/reddit-app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  type: LoadBalancer
  selector:
    app: reddit-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000