apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: mlflow-server
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        args:
          - "mlflow"
          - "server"
          - "--host=0.0.0.0"
          - "--port=5000"
          - "--backend-store-uri=sqlite:///mlflow.db"
          - "--default-artifact-root=file:/mlflow/mlruns"
        volumeMounts:
        - name: mlruns
          mountPath: /mlflow/mlruns
      volumes:
      - name: mlruns
        emptyDir: {}