stages:
  prepare:
    cmd: python src/preprocessing.py
    deps:
      - data/world_happiness_report.csv
      - src/preprocessing.py
    outs:
      - data/pipeline.pkl
      - data/processed_world_happiness_train_data.csv
      - data/processed_world_happiness_test_data.csv